site_name: "The networthdash package"

nav:
  - Home: index.md
  - Visualisation guide: visualisation.md
  - Code reference: reference.md
  - CSV description: csv.md
  - Changelog: CHANGELOG.md

theme:
  name: "mkdocs"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy

docs_dir: "docs"
site_dir: "_site"
