
name: CI Lint with Ruff

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Hatch
        run: pipx install hatch
      - name: Lint with Ruff
        run: |
          cd src
          hatch fmt
      - name: Autocommit fixes 
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'style fixes by ruff'
